version: '3'

services:
  app:
    container_name: php-container-eusipro
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
    networks:
      - container-eusipro-net
  mysql:
    image: mysql:5.7.22
    container_name: mysql-container-eusipro
    restart: unless-stopped
    ports:
      - "3308:3306"
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # ${DB_PASSWORD}
      SERVICE_NAME: mysql
    networks:
      - container-eusipro-net
networks:
  container-eusipro-net:
    driver: bridge
